### PR TITLE
Update to the networkProfile

### PR DESCRIPTION
**Pull request by krishvoor**
Updates the following in the networkProfile:

```
"networkPolicy": "cilium",
"networkDataplane": "cilium",
"networkPluginMode": "overlay",
```

### CODE REVIEW

**Comment by mukrishn** [comment]
Also change `osDiskType` to `Ephemeral`

**Comment by krishvoor** [comment]
> Also change `osDiskType` to `Ephemeral`

Done added, ptal at the instance type as well.
Made them as `Standard_D8s_v3` across userpool and agentpool

**Comment by mukrishn** [comment]
> Done added, ptal at the instance type as well.
Made them as Standard_D8s_v3 across userpool and agentpool

Now please commit and push :)

**Comment by krishvoor** [comment]
Something got messed up, ptal here : https://github.com/mukrishn/arohcp-workspace/pull/9

**Pull request closed without merging**
