### PR TITLE
Reworking the deployment logic

### PR DESCRIPTION
**Pull request by krishvoor**

### CODE REVIEW

**Comment by krishvoor** [comment]
@mukrishn @morenod - I need to add few more changes to PR, then will request for your review.

**Comment by krishvoor** [comment]
``` 
$ kubectl get po -n hcp-density-aks-0 --no-headers | wc -l
     130
$ kubectl get cm -n hcp-density-aks-0 --no-headers | wc -l
     116
$ kubectl get secret -n hcp-density-aks-0 --no-headers | wc -l
     114
$ kubectl get deployment -n hcp-density-aks-0 --no-headers | wc -l
      42
$ kubectl get svc -n hcp-density-aks-0 --no-headers | wc -l
      42
$
 ```

**Comment by krishvoor** [comment]
@mukrishn @morenod 
I have verified the above changes, they are working as expected.
We have the following objects getting created.

- [x] Deployments 42
- [x] Service 46
- [x] Secrets 114
- [x] Configmaps 114
- [x] Pods 130

```
$ kubectl get secret -n hcp-density-aks-0 --no-headers | wc -l
     114
$ kubectl get service -n hcp-density-aks-0 --no-headers | wc -l
      46
$ kubectl get po -n hcp-density-aks-0 --no-headers | wc -l
     130
$ kubectl get deployment -n hcp-density-aks-0 --no-headers | wc -l
      42
$ kubectl get cm -n hcp-density-aks-0 --no-headers | wc -l
     115
$
```

**Review by morenod — APPROVED** [review]
LGTM

**Review by mukrishn — APPROVED** [review]

**Pull request merged**
